services:
  consul-server-1:
    image: hashicorp/consul:latest
    container_name: consul-server-1
    restart: unless-stopped
    networks:
      - vault_consul_network
    ports:
      - "${CONSUL_HTTP_PORT_1:-8500}:8500"
      - "${CONSUL_DNS_PORT:-8600}:8600/tcp"
      - "${CONSUL_DNS_PORT:-8600}:8600/udp"
    volumes:
      - consul_data_1:/consul/data
      - ./config/consul:/consul/config:ro
    command: agent -server -bootstrap-expect=3 -node=consul-1 -client=0.0.0.0 -ui
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  consul-server-2:
    image: hashicorp/consul:latest
    container_name: consul-server-2
    restart: unless-stopped
    networks:
      - vault_consul_network
    ports:
      - "${CONSUL_HTTP_PORT_2:-8510}:8500"
    volumes:
      - consul_data_2:/consul/data
      - ./config/consul:/consul/config:ro
    command: agent -server -retry-join=consul-server-1 -node=consul-2 -client=0.0.0.0
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    depends_on:
      - consul-server-1
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  consul-server-3:
    image: hashicorp/consul:latest
    container_name: consul-server-3
    restart: unless-stopped
    networks:
      - vault_consul_network
    ports:
      - "${CONSUL_HTTP_PORT_3:-8520}:8500"
    volumes:
      - consul_data_3:/consul/data
      - ./config/consul:/consul/config:ro
    command: agent -server -retry-join=consul-server-1 -node=consul-3 -client=0.0.0.0
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    depends_on:
      - consul-server-1
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vault-1:
    image: hashicorp/vault:latest
    container_name: vault-1
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    depends_on:
      consul-server-1:
        condition: service_healthy
      consul-server-2:
        condition: service_healthy
      consul-server-3:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_API_ADDR: http://vault-1:8200
      VAULT_CLUSTER_ADDR: https://vault-1:8201
      SKIP_SETCAP: 1
    ports:
      - "${VAULT_PORT_1:-8200}:8200"
      - "${VAULT_CLUSTER_PORT_1:-8201}:8201"
    volumes:
      - vault_logs:/vault/logs
      - ./config/vault:/vault/config:ro
      - ./policies:/vault/policies:ro
      - ./scripts:/vault/scripts:ro
      - ./tls:/vault/tls:ro
    command: server
    networks:
      - vault_consul_network
    healthcheck:
      test: ["CMD", "vault", "status", "-tls-skip-verify"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vault-2:
    image: hashicorp/vault:latest
    container_name: vault-2
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    depends_on:
      vault-1:
        condition: service_started
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_API_ADDR: http://vault-2:8200
      VAULT_CLUSTER_ADDR: https://vault-2:8201
      SKIP_SETCAP: 1
    ports:
      - "${VAULT_PORT_2:-8210}:8200"
      - "${VAULT_CLUSTER_PORT_2:-8211}:8201"
    volumes:
      - vault_logs:/vault/logs
      - ./config/vault:/vault/config:ro
      - ./policies:/vault/policies:ro
      - ./tls:/vault/tls:ro
    command: server
    networks:
      - vault_consul_network
    healthcheck:
      test: ["CMD", "vault", "status", "-tls-skip-verify"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vault-3:
    image: hashicorp/vault:latest
    container_name: vault-3
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    depends_on:
      vault-1:
        condition: service_started
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_API_ADDR: http://vault-3:8200
      VAULT_CLUSTER_ADDR: https://vault-3:8201
      SKIP_SETCAP: 1
    ports:
      - "${VAULT_PORT_3:-8220}:8200"
      - "${VAULT_CLUSTER_PORT_3:-8221}:8201"
    volumes:
      - vault_logs:/vault/logs
      - ./config/vault:/vault/config:ro
      - ./policies:/vault/policies:ro
      - ./tls:/vault/tls:ro
    command: server
    networks:
      - vault_consul_network
    healthcheck:
      test: ["CMD", "vault", "status", "-tls-skip-verify"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Initialize Vault
  vault-init:
    image: hashicorp/vault:latest
    container_name: vault-init
    depends_on:
      vault-1:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://vault-1:8200
      VAULT_SKIP_VERIFY: "true"
    volumes:
      - ./scripts:/scripts:ro
      - vault_keys:/vault/keys
    command: /scripts/init-vault-consul.sh
    networks:
      - vault_consul_network
    profiles:
      - init

  # HAProxy Load Balancer
  haproxy:
    image: haproxy:alpine
    container_name: vault-haproxy
    restart: unless-stopped
    ports:
      - "${HAPROXY_PORT:-80}:80"
      - "${HAPROXY_VAULT_PORT:-8200}:8200"
      - "${HAPROXY_CONSUL_PORT:-8500}:8500"
      - "${HAPROXY_STATS_PORT:-8404}:8404"
    volumes:
      - ./config/haproxy-consul.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - vault_consul_network
    depends_on:
      - vault-1
      - consul-server-1
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  consul_data_1:
    driver: local
  consul_data_2:
    driver: local
  consul_data_3:
    driver: local
  vault_logs:
    driver: local
  vault_keys:
    driver: local

networks:
  vault_consul_network:
    driver: bridge